---
title: "Tabroom Calc"
author: "Evans Chen"
date: "March 5, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r wrap-hook,echo=FALSE}
library(knitr)
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  # this hook is used only when the linewidth option is not NULL
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    # any lines wider than n should be wrapped
    if (any(nchar(x) > n)) x = strwrap(x, width = n)
    x = paste(x, collapse = '\n')
  }
  hook_output(x, options)
})
```

```{r,messages=FALSE, message = FALSE}
suppressWarnings(library(tidyverse))

if ( require(rvest) == FALSE ) {
  install.packages("rvest",repos="https://cloud.r-project.org")
  suppressWarnings(library(rvest))
}
```

```{r}
speakAvg = function(x){
  nums = x %>% strsplit(" ")
  res=(as.numeric(nums[[1]][1])+as.numeric(nums[[1]][2]))/2
  return (res)
}
```

```{r linewidth=80}
#Calculating the Speaks for round 1
#All the Pro Teams for round 1
page1 = read_html("https://www.tabroom.com/index/tourn/results/round_results.mhtml?tourn_id=13670&round_id=455260")
res = page1 %>% html_nodes("table") %>% .[1] %>% html_table()
team1=res[[1]]$Pro
team1=gsub("\\t","",team1)
team1=gsub("(\\n)+"," ",team1)

R1speakers1=strsplit(team1," ")
R1PSecondSpeaker = lapply(R1speakers1, FUN=function(x){x[length(x)]}) %>% unlist
R1PFirstSpeaker = lapply(R1speakers1, FUN=function(x){x[length(x)-2]}) %>% unlist

points1=res[[1]]$`Points/Ranks`
points1=gsub("\\t","",points1)
points1=gsub("(\\n)+"," ",points1)
points1=gsub("[^0-9]{2,}"," ",points1)
points1=gsub(" $","",points1)
points1=gsub(" ([0-9]|\\.)+$","",points1)
points1=gsub(" ([0-9]|\\.)+$","",points1)

speakSplit = function(x){
  nums = x %>% strsplit(" ")
  res = c(as.numeric(nums[[1]][1]),as.numeric(nums[[1]][2]))
}

round1 = points1 %>% lapply(FUN=speakSplit)
round1matrix = matrix(unlist(round1), ncol = length(round1)) %>% t

round1.df1 = data.frame(Team = team1, Speaker = R1PFirstSpeaker, Round_1_Points = round1matrix[,1])
round1.df2 = data.frame(Team = team1, Speaker = R1PSecondSpeaker, Round_1_Points = round1matrix[,2])

#All the Con Teams for round 1
team2=res[[1]]$Con
team2=gsub("\\t","",team2)
team2=gsub("(\\n)+"," ",team2)

R1speakers2=strsplit(team2," ")
R1CSecondSpeaker = lapply(R1speakers2, FUN=function(x){x[length(x)]}) %>% unlist
R1CFirstSpeaker = lapply(R1speakers2, FUN=function(x){x[length(x)-2]}) %>% unlist

points2=res[[1]]$`Points/Ranks`
points2=gsub("\\t","",points2)
points2=gsub("(\\n)+"," ",points2)
points2=gsub("[^0-9]{2,}"," ",points2)
points2=gsub(" $","",points2)
points2=gsub("^([0-9]|\\.)+ ","",points2)
points2=gsub("^([0-9]|\\.)+ ","",points2)

round1 = points2 %>% lapply(FUN=speakSplit)
round1matrix = matrix(unlist(round1), ncol = length(round1)) %>% t

round1.df3 = data.frame(Team = team2, Speaker = R1CFirstSpeaker, Round_1_Points = round1matrix[,1])
round1.df4 = data.frame(Team = team2, Speaker = R1CSecondSpeaker, Round_1_Points = round1matrix[,2])

final_round1 = rbind(round1.df1, round1.df2, round1.df3, round1.df4)
```

```{r}
#Calculating the Speaks for round 2
#All the Pro Teams for round 2
page1 = read_html("https://www.tabroom.com/index/tourn/results/round_results.mhtml?tourn_id=13670&round_id=455261")
res = page1 %>% html_nodes("table") %>% .[1] %>% html_table()
team1=res[[1]]$Pro
team1=gsub("\\t","",team1)
team1=gsub("(\\n)+"," ",team1)

R2speakers1=strsplit(team1," ")
R2PSecondSpeaker = lapply(R2speakers1, FUN=function(x){x[length(x)]}) %>% unlist
R2PFirstSpeaker = lapply(R2speakers1, FUN=function(x){x[length(x)-2]}) %>% unlist

points1=res[[1]]$`Points/Ranks`
points1=gsub("\\t","",points1)
points1=gsub("(\\n)+"," ",points1)
points1=gsub("[^0-9]{2,}"," ",points1)
points1=gsub(" $","",points1)
points1=gsub(" ([0-9]|\\.)+$","",points1)
points1=gsub(" ([0-9]|\\.)+$","",points1)

round2 = points1 %>% lapply(FUN=speakSplit)
round2matrix = matrix(unlist(round2), ncol = length(round2)) %>% t

round2.df1 = data.frame(Team = team1, Speaker = R2PFirstSpeaker, Round_2_Points = round2matrix[,1])
round2.df2 = data.frame(Team = team1, Speaker = R2PSecondSpeaker, Round_2_Points = round2matrix[,2])

#All the Con Teams for round 2
team2=res[[1]]$Con
team2=gsub("\\t","",team2)
team2=gsub("(\\n)+"," ",team2)

R2speakers2=strsplit(team2," ")
R2CSecondSpeaker = lapply(R2speakers2, FUN=function(x){x[length(x)]}) %>% unlist
R2CFirstSpeaker = lapply(R2speakers2, FUN=function(x){x[length(x)-2]}) %>% unlist

points2=res[[1]]$`Points/Ranks`
points2=gsub("\\t","",points2)
points2=gsub("(\\n)+"," ",points2)
points2=gsub("[^0-9]{2,}"," ",points2)
points2=gsub(" $","",points2)
points2=gsub("^([0-9]|\\.)+ ","",points2)
points2=gsub("^([0-9]|\\.)+ ","",points2)

round2 = points2 %>% lapply(FUN=speakSplit)
round2matrix = matrix(unlist(round2), ncol = length(round2)) %>% t

round2.df3 = data.frame(Team = team2, Speaker = R2CFirstSpeaker, Round_2_Points = round2matrix[,1])
round2.df4 = data.frame(Team = team2, Speaker = R2CSecondSpeaker, Round_2_Points = round2matrix[,2])

final_round2 = rbind(round2.df1, round2.df2, round2.df3, round2.df4)
final_round2
```

```{r}
#Calculating the Speaks for round 3
#All the Pro Teams for round 3
page1 = read_html("https://www.tabroom.com/index/tourn/results/round_results.mhtml?tourn_id=13670&round_id=455262")
res = page1 %>% html_nodes("table") %>% .[1] %>% html_table()
team1=res[[1]]$Pro
team1=gsub("\\t","",team1)
team1=gsub("(\\n)+"," ",team1)

R3speakers1=strsplit(team1," ")
R3PSecondSpeaker = lapply(R3speakers1, FUN=function(x){x[length(x)]}) %>% unlist
R3PFirstSpeaker = lapply(R3speakers1, FUN=function(x){x[length(x)-2]}) %>% unlist

points1=res[[1]]$`Points/Ranks`
points1=gsub("\\t","",points1)
points1=gsub("(\\n)+"," ",points1)
points1=gsub("[^0-9]{2,}"," ",points1)
points1=gsub(" $","",points1)
points1=gsub(" ([0-9]|\\.)+$","",points1)
points1=gsub(" ([0-9]|\\.)+$","",points1)

round3 = points1 %>% lapply(FUN=speakSplit)
round3matrix = matrix(unlist(round3), ncol = length(round3)) %>% t

round3.df1 = data.frame(Team = team1, Speaker = R3PFirstSpeaker, Round_3_Points = round3matrix[,1])
round3.df2 = data.frame(Team = team1, Speaker = R3PSecondSpeaker, Round_3_Points = round3matrix[,2])

#All the Con Teams for round 3
team2=res[[1]]$Con
team2=gsub("\\t","",team2)
team2=gsub("(\\n)+"," ",team2)

R3speakers2=strsplit(team2," ")
R3CSecondSpeaker = lapply(R3speakers2, FUN=function(x){x[length(x)]}) %>% unlist
R3CFirstSpeaker = lapply(R3speakers2, FUN=function(x){x[length(x)-2]}) %>% unlist

points2=res[[1]]$`Points/Ranks`
points2=gsub("\\t","",points2)
points2=gsub("(\\n)+"," ",points2)
points2=gsub("[^0-9]{2,}"," ",points2)
points2=gsub(" $","",points2)
points2=gsub("^([0-9]|\\.)+ ","",points2)
points2=gsub("^([0-9]|\\.)+ ","",points2)

round3 = points2 %>% lapply(FUN=speakSplit)
round3matrix = matrix(unlist(round3), ncol = length(round3)) %>% t

round3.df3 = data.frame(Team = team2, Speaker = R3CFirstSpeaker, Round_3_Points = round3matrix[,1])
round3.df4 = data.frame(Team = team2, Speaker = R3CSecondSpeaker, Round_3_Points = round3matrix[,2])

final_round3 = rbind(round3.df1, round3.df2, round3.df3, round3.df4)
final_round3
```

