---
title: "Testing File"
author: "Evans Chen"
date: "March 5, 2020"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r wrap-hook,echo=FALSE}
library(knitr)
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  # this hook is used only when the linewidth option is not NULL
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    # any lines wider than n should be wrapped
    if (any(nchar(x) > n)) x = strwrap(x, width = n)
    x = paste(x, collapse = '\n')
  }
  hook_output(x, options)
})
```

```{r}
#Testing merging and adding columns
teams1 = c("Team A","Team B", "Team C", "Team D")
teams2 = c("Team C","Team A", "Team D", "Team B")
teams3 = c("Team B","Team D", "Team A", "Team C")

speaker1 = c("Alex", "Joey", "Joshy", "Henry")
speaker2 = c("Joshy", "Alex", "Henry", "Joey")
speaker3 = c("Joey", "Henry", "Alex", "Joshy")
  
points1 = c(28,29,30,25)
points2 = c(25,30,30,26)
points3 = c(30,24,28,25)

round1 = data.frame(TeamName = teams1, Speaker = speaker1, Points = points1)
round2 = data.frame(TeamName = teams2, Speaker = speaker2, Points = points2)

rounds1_2=merge(round1,round2,by=c("TeamName","Speaker"), suffixes = c("1","2"))
#rounds1_2

round3 = data.frame(TeamName = teams3, Speaker = speaker3, Points = points3)
rounds1_3=merge(rounds1_2,round3,by=c("TeamName","Speaker"))
#rounds1_3
```

```{r}
#Testing merging and adding rows
teams1 = c("Team A","Team B", "Team C", "Team D")
teams2 = c("Team C","Team A", "Team D", "Team B")

speaker1 = c("Alex", "Joey", "Joshy", "Henry")
speaker2 = c("Lily", "Andrew", "Dan", "Steven")

points1 = c(28,29,30,25)
points2 = c(25,30,30,26)

round1.1 = data.frame(TeamName = teams1, Speaker = speaker1, Round1Points = points1)
round1.2 = data.frame(TeamName = teams2, Speaker = speaker2, Round1Points = points2)

round1final = rbind(round1.1, round1.2)
#round1final

#Testing mergine and adding columns, more information
teams3 = c("Team B","Team D", "Team A", "Team C")
teams4 = c("Team C","Team B", "Team A", "Team D")

speaker1 = c("Joey", "Henry", "Alex", "Joshy")
speaker2 = c("Lily", "Steven", "Andrew", "Dan")

points1 = c(25,27,28,30)
points2 = c(27,29.5,29,24)

round2.1 = data.frame(TeamName = teams3, Speaker = speaker1, Round2Points = points1)
round2.2 = data.frame(TeamName = teams4, Speaker = speaker2, Round2Points = points2)

round2final = rbind(round2.1, round2.2)
#round2final

#merge(round1final, round2final, by=c("TeamName","Speaker"))
```